all : 	
	cd libls && $(MAKE)
	cd libls_apps && $(MAKE)

doc :
	cd libls && $(MAKE) doc
	cd libls_apps && $(MAKE) doc

clean :
	cd libls && $(MAKE) clean
	cd libls_apps && $(MAKE) clean

.PHONY: all doc clean

